#!/bin/bash
#
function pinscopeusage () {

   echo 'Usage: pinscope [pin#..]

This script reads the specified pins every seconds. The parameter represents
the GPIO pin number, e.g. 17 for GPIO17.

The intent is to visualize the inputs to test that attached sensors work.

The default for the pin list is: 17 18.'
   exit
}

if [ "X$1" = X-h ] ; then
   pinscopeusage
fi
if [ "X$1" = X--help ] ; then
   pinscopeusage
fi

INPUTLIST="17 18"
INPUTCOUNT=2

if [ $# -gt 0 ]
then
   INPUTLIST=$*
   INPUTCOUNT=$#
fi

for i in $INPUTLIST
do
   echo $i > /sys/class/gpio/export
done

sleep 3

declare -A INPUTLOG

for i in $INPUTLIST
do
   echo in > /sys/class/gpio/gpio$i/direction
   INPUTLOG[gpio$i]=
done

resetall () {
   for i in $INPUTLIST
   do
      echo $i > /sys/class/gpio/unexport
   done
   exit 0
}

trap resetall sigint

while :
do
   clear
   HEADER="= `date` ==========================================================="
   echo ${HEADER:0:79}
   for i in $INPUTLIST
   do
      LOG=${INPUTLOG[gpio$i]}
      case `cat /sys/class/gpio/gpio$i/value` in
      1)
         LOG="${LOG}+"
         ;;
      0)
         LOG="${LOG}-"
         ;;
      esac
      if [ ${#LOG} -gt 70 ] ; then
         LOG=${LOG: -70}
      fi
      echo "GPIO $i: $LOG"
      INPUTLOG[gpio$i]=$LOG
   done
   sleep 1
done

